name: quikxchat
title: QuikxChat
base: core24
version: 0.2.3
license: AGPL-3.0
summary: Simple and secure messaging app
description: |
  QuikxChat is an open source, secure matrix messenger app. The app is easy to use, secure and decentralized.


  ## Features

  - Send all kinds of messages, images and files
  - Voice messages
  - Location sharing
  - Push notifications
  - Unlimited private and public group chats
  - Public channels with thousands of participants
  - Feature rich group moderation
  - Discover and join public groups
  - Dark mode
  - Simple QR codes for easy sharing
  - Custom emotes and stickers
  - Video calls support
  - Spaces
  - Compatible with Element, Nheko, NeoChat and all other Matrix apps
  - End to end encryption
  - Emoji verification & cross signing
  - And much more...


  ## QuikxChat - Privacy-focused messaging

  A secure, decentralized messaging app that puts your privacy first.

  No tracking, no ads, just simple and secure communication.

  Website: https://github.com/iquxae/quikx-chat

grade: stable
confinement: strict

platforms:
  amd64:
    build-on: amd64
  arm64:
    build-on: arm64

parts:
  flutter-git:
    source: https://github.com/flutter/flutter.git
    source-tag: 3.24.4
    source-depth: 1
    plugin: nil
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      mkdir -p $CRAFT_PART_INSTALL/usr/libexec
      cp -r $CRAFT_PART_SRC $CRAFT_PART_INSTALL/usr/libexec/flutter
      ln -s $CRAFT_PART_INSTALL/usr/libexec/flutter/bin/flutter $CRAFT_PART_INSTALL/usr/bin/flutter
      ln -s $CRAFT_PART_INSTALL/usr/libexec/flutter/bin/dart $CRAFT_PART_INSTALL/usr/bin/dart
      $CRAFT_PART_INSTALL/usr/bin/flutter doctor
    build-packages:
      - clang
      - cmake
      - curl
      - libgtk-3-dev
      - ninja-build
      - unzip
      - xz-utils
      - zip
    override-prime: ''

  quikxchat:
    after: [flutter-git]
    plugin: nil
    source: .
    override-build: |
      # Workaround for Flutter build error:
      rm -rf build

      flutter build linux --release -v
      mkdir -p $CRAFT_PART_INSTALL/bin/
      cp -r build/linux/*/release/bundle/* $CRAFT_PART_INSTALL/bin/
    build-packages:
      - libsecret-1-dev
      - libjsoncpp-dev
      - libssl-dev
      - curl
      - libpciaccess-dev
    build-snaps:
      - rustup
    stage-packages:
      - libsecret-1-0
      - libjsoncpp25
      - libpciaccess0

slots:
  dbus-svc:
    interface: dbus
    bus: session
    name: com.iquxae.quikxchat

apps:
  quikxchat:
    command: bin/quikxchat
    extensions: [ gnome ]
    plugs:
      - audio-playback
      - desktop
      - desktop-legacy
      - home
      - network
      - network-manager
      - network-manager-observe
      - opengl
      - removable-media
      - browser-support
      - password-manager-service
    slots:
      - dbus-svc
    # Workaround for:
    # https://github.com/flutter-webrtc/flutter-webrtc/issues/1212#issuecomment-1611899344
    environment:
      XDG_DATA_HOME: $SNAP_USER_DATA
      XDG_DATA_DIRS: $SNAP/usr/share
      GDK_GL: gles
      LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAP/lib:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET"