name: Build Windows Release
permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      build_windows:
        description: 'Build Windows version'
        required: true
        default: 'false'
        type: choice
        options:
        - 'true'
        - 'false'

jobs:
  build-windows:
    runs-on: windows-latest
    if: github.event.inputs.build_windows == 'true'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.1'
        channel: 'stable'
    
    - name: Enable Windows desktop
      run: flutter config --enable-windows-desktop
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Build Windows app
      run: flutter build windows --release
    
    - name: Create MSIX installer
      run: dart run msix:create
    
    - name: Upload MSIX installer
      uses: actions/upload-artifact@v4
      with:
        name: simple_messenger-installer
        path: build/windows/x64/runner/Release/*.msix