name: Build Windows

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.7'
        channel: 'stable'
        cache: true
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Build Windows
      run: flutter build windows --release
    
    - name: Create Installer with Inno Setup
      run: |
        choco install innosetup -y
        iscc windows/installer.iss
      shell: powershell
    
    - name: Upload Windows Installer
      uses: actions/upload-artifact@v4
      with:
        name: QuikxChat-Windows-Installer
        path: build/windows/installer/*.exe
        if-no-files-found: error
    
    - name: Upload Windows Portable
      uses: actions/upload-artifact@v4
      with:
        name: QuikxChat-Windows-Portable
        path: build/windows/x64/runner/Release/
        if-no-files-found: error
    
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/windows/installer/*.exe
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
